package GUI;

import NetInteraction.ClientEvents;
import NetInteraction.ClientManager;


import javax.swing.*;
import java.awt.*;
import java.util.Locale;
import java.util.ResourceBundle;


import static java.awt.Frame.MAXIMIZED_BOTH;

public class VisualizationForm {
    private final ClientEvents clientEvents;
    private final JFrame visualizationFrame;
    private JPanel visualizationPanel;
    private JPanel panel1;
    private JButton backButton;
    private final String language;
    final ResourceBundle bundleRu = ResourceBundle
            .getBundle("resources.resource", new Locale("ru", "RU"));
    final ResourceBundle bundleDe = ResourceBundle
            .getBundle("resources.resource", new Locale("de", "DE"));
    final ResourceBundle bundleEs = ResourceBundle
            .getBundle("resources.resource", new Locale("es", "MX"));
    final ResourceBundle bundleLt = ResourceBundle
            .getBundle("resources.resource", new Locale("lt", "LT"));

    public VisualizationForm(JFrame parent, ClientEvents clientEvents, Object languageIn) {
        this.clientEvents = clientEvents;
        language = languageIn.toString();
        $$$setupUI$$$();
        setupSelectedLanguages(language);
        ClientManager clientManager = clientEvents.getClientManager();
        visualizationFrame = new JFrame();
        visualizationFrame.setSize(600, 400);
        visualizationFrame.setExtendedState(MAXIMIZED_BOTH);
        visualizationFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        visualizationFrame.setLocationRelativeTo(null);
        visualizationFrame.setVisible(true);
        visualizationFrame.add(visualizationPanel);
        backButton.addActionListener(e -> {
            ((Graphics) panel1).getUpdateThread().interrupt();
            visualizationFrame.dispose();
            parent.setVisible(true);
        });
    }

    public void setupSelectedLanguages(String language) {
        switch (language) {
            case "Russian" -> backButton.setText(bundleRu.getString("back"));
            case "Lithuanian" -> backButton.setText(bundleLt.getString("back"));
            case "German" -> backButton.setText(bundleDe.getString("back"));
            case "Spanish (Mexico)" -> backButton.setText(bundleEs.getString("back"));
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        visualizationPanel = new JPanel();
        visualizationPanel.setLayout(new BorderLayout(0, 0));
        visualizationPanel.setMinimumSize(new Dimension(1920, 1080));
        visualizationPanel.setPreferredSize(new Dimension(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        visualizationPanel.add(panel2, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.NORTH);
        backButton = new JButton();
        backButton.setText("Назад");
        panel3.add(backButton, BorderLayout.WEST);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel3.add(panel4, BorderLayout.SOUTH);
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel4.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel4.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel4.add(spacer3, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel2.add(panel5, BorderLayout.CENTER);
        panel1.setPreferredSize(new Dimension(2000, 900));
        panel5.add(panel1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return visualizationPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        panel1 = new Graphics(clientEvents, new Dimension(2000, 900), language);
    }

}
