package GUI;

import Dependency.Command;
import NetInteraction.ClientEvents;
import NetInteraction.ClientManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;

import static java.awt.Frame.MAXIMIZED_BOTH;

public class MainForm {
    private JPanel mainPanel;
    private JComboBox languages;
    private JLabel user;
    private JButton visualization;
    private JButton commander;
    private JButton table;
    private JButton changeUserButton;
    private JLabel hello;
    private final JFrame main;
    private final ClientEvents clientEvents;
    private String language;
    final ResourceBundle bundleRu = ResourceBundle
            .getBundle("resources.resource", new Locale("ru", "RU"));
    final ResourceBundle bundleDe = ResourceBundle
            .getBundle("resources.resource", new Locale("de", "DE"));
    final ResourceBundle bundleEs = ResourceBundle
            .getBundle("resources.resource", new Locale("es", "MX"));
    final ResourceBundle bundleLt = ResourceBundle
            .getBundle("resources.resource", new Locale("lt", "LT"));

    public MainForm(JFrame parent, ClientEvents clientEvents, Object languageIn) {
        this.clientEvents = clientEvents;
        ClientManager clientManager = clientEvents.getClientManager();
        this.language = languageIn.toString();
        main = new JFrame();
        main.setSize(600, 400);
        main.setExtendedState(MAXIMIZED_BOTH);
        user.setText(clientManager.getLogin());
        commander.addActionListener(new CommanderListener());
        table.addActionListener(new TableListener());
        visualization.addActionListener(new VisualisationListener());
        main.add(mainPanel);
        main.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        main.setLocationRelativeTo(null);
        main.setVisible(true);
        changeUserButton.addActionListener(e -> {
            main.dispose();
            AuthorizationForm form = new AuthorizationForm(clientEvents, language);
        });
        languages.addActionListener(e -> {
            language = languages.getSelectedItem().toString();
            setupSelectedLanguages(language);
        });
        languages.setSelectedItem(languageIn);
    }

    public void setupSelectedLanguages(String language) {
        switch (language) {
            case "Russian" -> {
                hello.setText(bundleRu.getString("hi"));
                table.setText(bundleRu.getString("tableButton"));
                visualization.setText(bundleRu.getString("visualButton"));
                commander.setText(bundleRu.getString("commandButton"));
                changeUserButton.setText(bundleRu.getString("changeUser"));
            }
            case "German" -> {
                hello.setText(bundleDe.getString("hi"));
                table.setText(bundleDe.getString("tableButton"));
                visualization.setText(bundleDe.getString("visualButton"));
                commander.setText(bundleDe.getString("commandButton"));
                changeUserButton.setText(bundleDe.getString("changeUser"));
            }
            case "Lithuanian" -> {
                hello.setText(bundleLt.getString("hi"));
                table.setText(bundleLt.getString("tableButton"));
                visualization.setText(bundleLt.getString("visualButton"));
                commander.setText(bundleLt.getString("commandButton"));
                changeUserButton.setText(bundleLt.getString("changeUser"));
            }
            case "Spanish (Mexico)" -> {
                hello.setText(bundleEs.getString("hi"));
                table.setText(bundleEs.getString("tableButton"));
                visualization.setText(bundleEs.getString("visualButton"));
                commander.setText(bundleEs.getString("commandButton"));
                changeUserButton.setText(bundleEs.getString("changeUser"));
            }
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setPreferredSize(new Dimension(150, 70));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.NORTH);
        languages = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Russian");
        defaultComboBoxModel1.addElement("Lithuanian");
        defaultComboBoxModel1.addElement("German");
        defaultComboBoxModel1.addElement("Spanish (Mexico)");
        languages.setModel(defaultComboBoxModel1);
        panel1.add(languages, BorderLayout.WEST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setAlignmentX(0.5f);
        panel1.add(panel2, BorderLayout.EAST);
        user = new JLabel();
        user.setText("Label");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(user, gbc);
        hello = new JLabel();
        hello.setInheritsPopupMenu(false);
        hello.setText("Приветствуем:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(hello, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel3, gbc);
        changeUserButton = new JButton();
        changeUserButton.setText("Сменить пользователя");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(changeUserButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer1, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        mainPanel.add(panel4, BorderLayout.CENTER);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(panel5, gbc);
        table = new JButton();
        table.setPreferredSize(new Dimension(220, 30));
        table.setText("Таблица");
        panel5.add(table);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(panel6, gbc);
        visualization = new JButton();
        visualization.setPreferredSize(new Dimension(220, 30));
        visualization.setText("Визуализация");
        panel6.add(visualization);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(panel7, gbc);
        commander = new JButton();
        commander.setPreferredSize(new Dimension(220, 30));
        commander.setText("Выполнение команд");
        panel7.add(commander);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        mainPanel.add(panel8, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    class TableListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                clientEvents.commandMode(new Command("getCollectionForTable"));
            } catch (IOException | ClassNotFoundException ioException) {
                ioException.printStackTrace();
            }
            main.dispose();
            main.setVisible(false);
            TableForm tableForm = new TableForm(main, clientEvents, language);
        }
    }

    class VisualisationListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                clientEvents.commandMode(new Command("getCollectionForTable"));
            } catch (IOException | ClassNotFoundException ioException) {
                ioException.printStackTrace();
            }
            main.dispose();
            main.setVisible(false);
            VisualizationForm visualizationForm = new VisualizationForm(main, clientEvents, language);
        }
    }

    class CommanderListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                clientEvents.commandMode(new Command("getCollectionForTable"));
            } catch (IOException | ClassNotFoundException ioException) {
                ioException.printStackTrace();
            }
            main.dispose();
            main.setVisible(false);
            CommanderForm commanderForm = new CommanderForm(main, clientEvents, language);
        }
    }

}
